% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{report}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={TradeData},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{TradeData}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2024-12-10 08:59:59.199798}

\begin{document}
\maketitle

\chapter{Data report overview}\label{data-report-overview}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3472}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Number of observations & 64164 \\
Number of variables & 8 \\
\end{longtable}

\subsection{Checks performed}\label{checks-performed}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.3649}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0811}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1149}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0676}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0743}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
character
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
haven labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
numeric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
integer
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
logical
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Date
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Identify miscoded missing values & \(\times\) & \(\times\) & \(\times\)
& \(\times\) & \(\times\) & \(\times\) & & \(\times\) \\
Identify prefixed and suffixed whitespace & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify levels with \textless{} 6 obs. & \(\times\) & \(\times\) &
\(\times\) & \(\times\) & & & & \\
Identify case issues & \(\times\) & \(\times\) & \(\times\) & \(\times\)
& & & & \\
Identify misclassified numeric or integer variables & \(\times\) &
\(\times\) & \(\times\) & \(\times\) & & & & \\
Identify outliers & & & & & \(\times\) & \(\times\) & & \(\times\) \\
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\chapter{Summary table}\label{summary-table}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.5866}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0950}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1006}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1285}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0894}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Variable class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\# unique values
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Missing observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Any problems?
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\hyperref[entity]{Entity} & character & 314 & 0.00 \% & \(\times\) \\
\hyperref[code]{Code} & character & 261 & 7.14 \% & \(\times\) \\
\hyperref[year]{Year} & numeric & 799 & 0.00 \% & \(\times\) \\
\hyperref[value-of-global-merchandise-exports-as-a-share-of-gdp-fouquin-and-hugot-cepii-2016-national-data]{Value
of global merchandise exports as a share of GDP (Fouquin and Hugot;
CEPII 2016; National data)} & numeric & 13767 & 78.48 \% & \(\times\) \\
\hyperref[gdp-per-capita]{GDP per capita} & numeric & 14338 & 66.36 \% &
\(\times\) \\
\hyperref[annotations]{900793-annotations} & logical & 1 & 100.00 \% &
\(\times\) \\
\hyperref[population-historical]{Population (historical)} & numeric &
54150 & 7.77 \% & \(\times\) \\
\hyperref[world-regions-according-to-owid]{World regions according to
OWID} & character & 7 & 99.58 \% & \\
\end{longtable}

\chapter{Variable list}\label{variable-list}

\section{Entity}\label{entity}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 314 \\
Mode & ``United Kingdom'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-1-Entity-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "Akrotiri and Dhekelia", "Aland Islands", "British Indian Ocean
  Territory", "Christmas Island", "Cocos Islands", \ldots, "Orange Free
  State", "Pakistan (former)", "Pitcairn", "Republic of Vietnam", "South
  Georgia and the South Sandwich Islands" (14 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{Code}\label{code}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 4584 (7.14 \%) \\
Number of unique values & 260 \\
Mode & ``GBR'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-2-Code-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations: "ALA",
  "CCK", "CXR", "IOT", "NFK", "OWID\_AKD", "OWID\_KRU", "OWID\_RVN",
  "PCN", "SGS".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{Year}\label{year}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 799 \\
Median & 1895 \\
1st and 3rd quartiles & 1820; 1965 \\
Min. and max. & -10000; 2023 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-3-Year-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "-10000", "-9000", "-8000", "-7000", "-6000", \ldots, "1480", "1481",
  "1482", "1483", "1484" (250 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{Value of global merchandise exports as a share of GDP (Fouquin
and Hugot; CEPII 2016; National
data)}\label{value-of-global-merchandise-exports-as-a-share-of-gdp-fouquin-and-hugot-cepii-2016-national-data}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 50356 (78.48 \%) \\
Number of unique values & 13766 \\
Median & 19.03 \\
1st and 3rd quartiles & 11.16; 31.36 \\
Min. and max. & 0; 779.76 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-4-Value-of-global-merchandise-exports-as-a-share-of-GDP-(Fouquin-and-Hugot;-CEPII-2016;-National-data)-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "0",
  "0", "0", "0", "0.01", \ldots, "466.03", "519.64", "564.11", "710.56",
  "779.76" (315 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{GDP per capita}\label{gdp-per-capita}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 42578 (66.36 \%) \\
Number of unique values & 14337 \\
Median & 2617.94 \\
1st and 3rd quartiles & 1470; 7231.69 \\
Min. and max. & 295; 160051.23 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-5-GDP-per-capita-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "295",
  "377.58", "391.09", "403.6", "413.83", \ldots, "155533", "155657.12",
  "157712.9", "159800.19", "160051.23" (483 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{900793-annotations}\label{annotations}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{Population (historical)}\label{population-historical}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 4987 (7.77 \%) \\
Number of unique values & 54149 \\
Median & 1436149 \\
1st and 3rd quartiles & 151010; 6946661 \\
Min. and max. & 1; 8091734935 \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-7-Population-(historical)-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "90741242", "90791250", "90834164", "90849785", "90862449", \ldots,
  "7811293714", "7887001284", "7954448405", "8021407170", "8091734935"
  (3970 values omitted).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\section{World regions according to
OWID}\label{world-regions-according-to-owid}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & character \\
Number of missing obs. & 63893 (99.58 \%) \\
Number of unique values & 6 \\
Mode & ``Europe'' \\
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{dataMaid_TradeData_files/figure-latex/Var-8-World-regions-according-to-OWID-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: VMuffin (username: \texttt{Vasudha}).
\item
  Report creation time: Tue Dec 10 2024 09:00:01
\item
  Report was run from directory:
  \texttt{C:/Users/vasud/OneDrive/Desktop/U-M\ -\ ALL/STATS\ 506/Final\ Project\ Data}
\item
  dataMaid v1.4.1 {[}Pkg: 2021-10-08 from CRAN (R 4.4.2){]}
\item
  R version 4.4.2 (2024-10-31 ucrt).
\item
  Platform: x86\_64-w64-mingw32/x64(America/New\_York).
\item
  Function call:
  \texttt{makeDataReport(data\ =\ TradeData,\ output\ =\ "pdf",\ replace\ =\ TRUE)}
\end{itemize}

\end{document}
